#!/usr/bin/env bash
# Script that installs and configures Nginx web server
# Install Nginx
apt-get update
apt-get -y install nginx
# listen on port 80
sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/defult
ufw allow 'Nginx HTTP'
# Configure Nginx to listen on port 80 and return "Hello World!" at the root
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
service nginx restart
