#!/usr/bin/env bash
# Script that configures an Nginx server to handle a custom 404 page
# Install Nginx
apt-get update
apt-get -y install nginx

# Create a custom 404 page with the string "Ceci n'est pas une page"
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Configure Nginx to use the custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    root /var/www/html;
    index index.html index.htm;
}" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
