#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes,
# displaying hours from 0 to 12 and minutes from 1 to 59.

hour=0
while [ $hour -lt 12 ]
do
  echo "Hour: $hour"
  for ((minute=1; minute<=59; minute++))
  do
    echo $minute
  done
  hour=$((hour + 1))
done
