#!/usr/bin/env bash
# Edit hosts file

sudo sed -i 's/.*localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts
echo '8.8.8.8 facebook.com' | sudo tee -a /etc/hosts > /dev/null
