#!/usr/bin/env bash

# Stop Nginx service
service nginx stop

# Change ownership of Nginx directories to nginx user
chown -R nginx:nginx /var/log/nginx /var/lib/nginx /etc/nginx

# Modify Nginx configuration to run as nginx user and listen on port 8080
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

# Start Nginx service
service nginx start
